"""Stage 9 -- the five publication figures.

Every number drawn by this module is either READ from a file in `results/` or
REGENERATED by calling the pipeline's own modules on the pipeline's own inputs.
Nothing is transcribed from a report's prose and nothing is hardcoded; the two
quantities that are not in any results file (the per-genome presence vectors of the
lead pair, and the identity of the recurrent ICP0g2 variant) are computed here from
`data/raw/*.fasta` through `src.benchmark_sacas9.presence_matrix` and an exact
pigeonhole search, and each figure's data function says so in its own docstring.

Layout
------
`figN_data()`  -> a plain dict of the values the figure plots, with provenance.
                  These are what `tests/test_figures.py` checks. They touch no
                  matplotlib state and can be called on their own.
`draw_figN(d)` -> a matplotlib Figure built from that dict.
`main()`       -> writes figures/figN.png (300 dpi) and figures/figN.pdf (vector).

Determinism
-----------
Output is byte-identical on re-run: no timestamp or per-run metadata is written into
either format (`_MPL_METADATA`), the bundled DejaVu font is used rather than a system
font, hash-salted ids are pinned, and nothing in the module samples a random number.
`python src/figures.py --check-deterministic` renders twice and compares digests.

Accessibility
-------------
Marks use the Okabe-Ito colourblind-safe palette; every coloured series is also
distinguished by marker or line style and carries a direct label or legend entry, so
identity is never conveyed by colour alone.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import matplotlib  # noqa: E402

matplotlib.use("Agg")

# fontTools logs one INFO line per glyph table per embedded subset; at five figures
# that is thousands of lines that bury the module's own progress output.
logging.getLogger("fontTools").setLevel(logging.WARNING)
logging.getLogger("matplotlib").setLevel(logging.WARNING)

import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
from matplotlib.patches import Rectangle  # noqa: E402

from src.common import (  # noqa: E402
    DEFAULT_CONSERVATION,
    DEFAULT_MANIFEST,
    PROJECT_ROOT,
    RESULTS_DIR,
    revcomp,
    setup_logging,
)
from src.escape import binomial_upper_bound  # noqa: E402
from src.nuclease import get_nuclease  # noqa: E402

LOG = logging.getLogger("figures")

FIGURE_DIR = PROJECT_ROOT / "figures"

#: The published lead pair, by site id in the stage-6 pool. Same constants as
#: `src.reconcile`; imported there rather than redefined would create a circular
#: dependency on a module that rebuilds the escape model, so they are re-stated and
#: `tests/test_figures.py` asserts they still agree.
ICP0G2 = "RL2_4496+"
ICP27G1 = "UL54_115156+"

#: Thresholds drawn on figure 1. They are the ones stage 7 itself tabulates
#: (`--thresholds` default, echoed in results/escape_summary.json's `minimum_k`).
FIG1_THRESHOLDS = (1e-3, 1e-6)

# Okabe-Ito, the standard colourblind-safe qualitative palette, in fixed assignment
# order. Every adjacent pair clears the deuteranope, protanope and tritanope
# separation floor; the two reserve slots are declared so a sixth series can never be
# invented on the spot. Hue is always paired with a marker or dash pattern, because
# these six are safe against colour blindness, not against a greyscale reprint.
BLUE = "#0072B2"
VERMILLION = "#D55E00"
GREEN = "#009E73"
ORANGE = "#E69F00"
PURPLE = "#CC79A7"   # reserve
SKY = "#56B4E9"      # reserve
INK = "#1a1a1a"
MUTED = "#6b6b6b"
FAINT = "#c8c8c8"

#: No creation date, no software banner: the bytes must not depend on when the
#: figure was rendered. matplotlib omits a key whose value is None.
_MPL_PDF_METADATA = {"CreationDate": None, "Creator": None, "Producer": None}
_MPL_PNG_METADATA = {"Software": None}

RC = {
    "font.family": "DejaVu Sans",
    "font.size": 7.0,
    "axes.titlesize": 8.0,
    "axes.labelsize": 7.0,
    "xtick.labelsize": 6.5,
    "ytick.labelsize": 6.5,
    "legend.fontsize": 6.5,
    "axes.linewidth": 0.6,
    "xtick.major.width": 0.6,
    "ytick.major.width": 0.6,
    "xtick.major.size": 2.5,
    "ytick.major.size": 2.5,
    "lines.linewidth": 1.4,
    "axes.edgecolor": INK,
    "axes.labelcolor": INK,
    "text.color": INK,
    "xtick.color": INK,
    "ytick.color": INK,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "legend.frameon": False,
    "figure.dpi": 300,
    "savefig.dpi": 300,
    "svg.hashsalt": "hsv-figures",
    "pdf.fonttype": 42,
    "ps.fonttype": 42,
    "path.simplify": False,
}

#: Single-column width. Journals typically set 85 mm; every figure is authored at
#: exactly that width so what is checked is what is printed.
COL_IN = 85.0 / 25.4

#: Panel titles are placed in axes coordinates at a NEGATIVE x so that they start at
#: the figure's left edge rather than at the plot area's, which on an 85 mm figure is
#: the difference between a title that fits and one the journal crops.
TITLE_X = -0.44


def _title_x(left: float, right: float, target: float = 0.015) -> float:
    """Axes-fraction x that puts a left-aligned title at figure fraction `target`."""
    return (target - left) / (right - left)


# --------------------------------------------------------------------------------------
# Small IO helpers
# --------------------------------------------------------------------------------------


def _need(path: Path, produced_by: str) -> Path:
    if not path.is_file():
        raise SystemExit(f"{path} not found. Run {produced_by} first.")
    return path


def _tsv(path: Path, produced_by: str) -> pd.DataFrame:
    return pd.read_csv(_need(path, produced_by), sep="\t")


def _load_genome_seqs(manifest: pd.DataFrame) -> dict[str, str]:
    """Accession -> upper-case genome string, in manifest order.

    Uses `src.conservation.load_genome` so the sequence normalisation (case, line
    joining, ambiguity symbols left intact) is identical to stage 3's.
    """
    from src.conservation import load_genome

    out: dict[str, str] = {}
    for row in manifest.itertuples(index=False):
        out[str(row.accession)] = load_genome(PROJECT_ROOT / str(row.fasta_path))
    return out


# --------------------------------------------------------------------------------------
# Figure 1 -- the resolution floor
# --------------------------------------------------------------------------------------


def fig1_data() -> dict:
    """P(escape) versus guide count k: point estimate and certifiable bound.

    Point estimate: read verbatim from `results/escape_k_curve.tsv`
    (`p_escape_best`), which stage 7 wrote.

    Certifiable bound: NOT stored in any results file -- stage 7 renders it straight
    into section 7.1 of `results/escape_model_report.md`. It is regenerated here with
    stage 7's own arithmetic and stage 7's own function:

        absences_i = n_strains_total - n_strains_present   (results/sacas9-20nt/
                                                            conservation.tsv)
        u_i        = binomial_upper_bound(absences_i, N)   (src.escape, Clopper-
                                                            Pearson 95% upper limit)
        bound(S)   = PROD_i [ u_i + (1 - u_i) * q_i ]      (q_i = q_site, results/
                                                            escape_site_parameters.tsv)

    which is line-for-line the `absence_upper` / `floor_rows` block of
    `src.escape.assemble_context`. `tests/test_figures.py` checks the regenerated
    values against the numbers stage 7 printed in its own report.

    The k=1 sites of the best sets are all present in 183/183 genomes, so every u_i
    is the same rule-of-three bound, 0.0162 -- the "site absent in 0/183 treated as
    having population absence frequency 0.0162" of the figure specification. That is
    a property of the data, read off it, not an assumption applied to it.
    """
    curve = _tsv(RESULTS_DIR / "escape_k_curve.tsv", "run_pipeline.py --escape")
    params = _tsv(RESULTS_DIR / "escape_site_parameters.tsv",
                  "run_pipeline.py --escape")
    cons = _tsv(RESULTS_DIR / "sacas9-20nt" / "conservation.tsv",
                "run_pipeline.py --nuclease sacas9 --spacer-length 20 --skip-fetch")

    q = dict(zip(params["guide_id"], params["q_site"]))
    present = dict(zip(cons["guide_id"], cons["n_strains_present"]))
    n_genomes = int(cons["n_strains_total"].iloc[0])

    ub_cache: dict[int, float] = {}

    def absence_upper(absences: int) -> float:
        if absences not in ub_cache:
            ub_cache[absences] = binomial_upper_bound(absences, n_genomes)
        return ub_cache[absences]

    ks, point, bound, absences_per_k = [], [], [], []
    for row in curve.itertuples(index=False):
        guides = str(row.guides).split(";")
        missing = [g for g in guides if g not in q or g not in present]
        if missing:
            raise SystemExit(
                f"k={row.k}: no q_site/conservation for {missing}; the k-curve and "
                "the site tables come from different runs.")
        ub = 1.0
        absent_counts = []
        for g in guides:
            a = n_genomes - int(present[g])
            absent_counts.append(a)
            u = absence_upper(a)
            ub *= u + (1.0 - u) * float(q[g])
        ks.append(int(row.k))
        point.append(float(row.p_escape_best))
        bound.append(ub)
        absences_per_k.append(absent_counts)

    ks_a = np.asarray(ks, dtype=int)
    point_a = np.asarray(point, dtype=float)
    bound_a = np.asarray(bound, dtype=float)

    def first_below(vals: np.ndarray, t: float) -> int | None:
        hit = np.flatnonzero(vals < t)
        return int(ks_a[hit[0]]) if hit.size else None

    crossings = {t: {"point": first_below(point_a, t), "bound": first_below(bound_a, t)}
                 for t in FIG1_THRESHOLDS}

    return {
        "k": ks_a,
        "p_point": point_a,
        "p_bound": bound_a,
        "n_genomes": n_genomes,
        "rule_of_three": absence_upper(0),
        "absences_per_k": absences_per_k,
        "thresholds": tuple(FIG1_THRESHOLDS),
        "crossings": crossings,
        "guides": [str(g) for g in curve["guides"]],
    }


def draw_fig1(d: dict) -> "plt.Figure":
    fig, ax = plt.subplots(figsize=(COL_IN, 2.85))
    k = d["k"]

    for t in d["thresholds"]:
        ax.axhline(t, color="#b4b4b4", lw=0.8, ls=(0, (4, 3)), zorder=1,
                   xmax=0.90)
        ax.text(k[-1] + 0.42, t, f"$10^{{{int(round(np.log10(t)))}}}$",
                va="center", ha="left", fontsize=6, color=MUTED, clip_on=False)

    ax.plot(k, d["p_bound"], color=VERMILLION, lw=1.5, ls=(0, (5, 2)),
            marker="s", ms=3.6, mfc="white", mew=1.2, mec=VERMILLION,
            zorder=3, label="certifiable bound (95% CI)")
    ax.plot(k, d["p_point"], color=BLUE, lw=1.5, marker="o", ms=3.8,
            mfc="white", mew=1.2, mec=BLUE, zorder=4,
            label="point estimate (measured absences)")

    ax.set_yscale("log")
    ax.set_xlabel("number of guides, $k$")
    ax.set_ylabel("P(escape) per exposed viral genome")
    ax.set_xticks(k)
    ax.set_xlim(k[0] - 0.35, k[-1] + 1.15)

    lo = min(d["p_point"].min(), d["p_bound"].min())
    hi = max(d["p_point"].max(), d["p_bound"].max())
    ax.set_ylim(10 ** (np.floor(np.log10(lo)) - 0.6), 10 ** (np.ceil(np.log10(hi)) + 0.4))
    ax.set_yticks([10.0 ** e for e in range(int(np.floor(np.log10(lo))),
                                            int(np.ceil(np.log10(hi))) + 1, 3)])
    ax.grid(axis="y", color=FAINT, lw=0.4, alpha=0.45, zorder=0)
    ax.set_axisbelow(True)

    # Annotate the 1e-6 crossings -- the paper's headline: one more guide is needed
    # before the corpus can certify what the point estimate already claims.
    t = 1e-6
    kp = d["crossings"][t]["point"]
    kb = d["crossings"][t]["bound"]
    if kp is not None and kb is not None:
        yp = d["p_point"][list(k).index(kp)]
        yb = d["p_bound"][list(k).index(kb)]
        for kk, yy, col in ((kp, yp, BLUE), (kb, yb, VERMILLION)):
            ax.plot([kk], [yy], marker="o", ms=9.0, mfc="none", mec=col,
                    mew=1.0, zorder=5)
        ax.annotate(f"point estimate reaches\n$10^{{-6}}$ at $k$ = {kp}",
                    xy=(kp, yp), xytext=(kp - 1.95, yp / 400),
                    fontsize=6, color=BLUE, ha="left", va="top",
                    arrowprops=dict(arrowstyle="-", lw=0.7, color=BLUE,
                                    shrinkA=1, shrinkB=6))
        ax.annotate(f"the corpus can certify it\nonly at $k$ = {kb}", xy=(kb, yb),
                    xytext=(kb + 1.05, yb * 320), fontsize=6, color=VERMILLION,
                    ha="left", va="bottom",
                    arrowprops=dict(arrowstyle="-", lw=0.7, color=VERMILLION,
                                    shrinkA=1, shrinkB=6))

    ax.legend(loc="lower left", handlelength=2.0, labelspacing=0.6,
              borderaxespad=0.35, handletextpad=0.5)
    ax.set_title("Resolution floor of a %d-genome corpus" % d["n_genomes"],
                 loc="left", pad=5)
    fig.text(0.012, 0.018,
             "A site absent in 0/%d isolates is still consistent with a population\n"
             "absence frequency up to %.4f (Clopper–Pearson 95%% upper limit); the\n"
             "bound re-runs the escape model with every site set to that value."
             % (d["n_genomes"], d["rule_of_three"]),
             fontsize=5.3, color=MUTED, va="bottom", ha="left", linespacing=1.4)
    fig.subplots_adjust(left=0.175, right=0.935, top=0.915, bottom=0.295)
    return fig


# --------------------------------------------------------------------------------------
# Figure 2 -- joint versus marginal coverage
# --------------------------------------------------------------------------------------


def fig2_data() -> dict:
    """Per-genome presence of the published lead pair across all 183 isolates.

    The per-genome presence VECTORS are in no results file. `absent_in` in
    `results/sacas9_benchmark_pool.tsv` and `results/*/conservation.tsv` is
    deliberately truncated to the first 25 accessions
    (`score_conservation(record_absences=25)`, and the same cap in
    `benchmark_sacas9`), so it under-reports ICP0g2, which is absent in 28. The
    matrix is therefore rebuilt from `data/raw/*.fasta` by calling the pipeline's own
    `src.benchmark_sacas9.presence_matrix` on a two-row pool -- stage-3 exact
    both-strand target-site semantics, same nuclease grammar, same genome order.

    The marginals it produces are checked against the published
    `conservation_complete_genomes`, and the joint against
    `joint_conservation` in `results/sacas9_benchmark_pairs.tsv`.
    """
    from src.benchmark_sacas9 import presence_matrix

    pool = _tsv(RESULTS_DIR / "sacas9_benchmark_pool.tsv",
                "run_pipeline.py --benchmark-sacas9")
    manifest = _tsv(DEFAULT_MANIFEST, "run_pipeline.py (stage 1)")
    pairs = _tsv(RESULTS_DIR / "sacas9_benchmark_pairs.tsv",
                 "run_pipeline.py --benchmark-sacas9")

    sub = pool[pool["guide_id"].isin([ICP0G2, ICP27G1])]
    if len(sub) != 2:
        raise SystemExit(f"Expected both lead guides in the stage-6 pool, found {len(sub)}.")
    nuclease = get_nuclease("sacas9", spacer_length=len(sub["protospacer"].iloc[0]))

    accessions, mat, index = presence_matrix(sub[["guide_id", "target_site"]],
                                             manifest, nuclease)
    icp0 = mat[:, index[ICP0G2]]
    icp27 = mat[:, index[ICP27G1]]

    published = dict(zip(pool["guide_id"], pool["conservation_complete_genomes"]))
    prow = pairs[(pairs["icp0_guide"] == ICP0G2) & (pairs["icp27_guide"] == ICP27G1)]
    if prow.empty:
        raise SystemExit("The published lead pair is missing from sacas9_benchmark_pairs.tsv.")

    marg = {ICP0G2: float(icp0.mean()), ICP27G1: float(icp27.mean())}
    joint = float((icp0 & icp27).mean())

    # Column order that makes the non-overlap visible: both present, then the
    # isolates each guide alone misses, then any missed by both.
    group = np.where(icp0 & icp27, 0, np.where(~icp0 & icp27, 1,
                     np.where(icp0 & ~icp27, 2, 3)))
    order = np.lexsort((np.arange(len(group)), group))

    return {
        "accessions": [str(a) for a in accessions],
        "icp0_present": icp0,
        "icp27_present": icp27,
        "order": order,
        "group": group,
        "n_genomes": int(mat.shape[0]),
        "marginals": marg,
        "published_marginals": {g: float(published[g]) for g in (ICP0G2, ICP27G1)},
        "product_of_marginals": float(marg[ICP0G2] * marg[ICP27G1]),
        "joint": joint,
        "published_joint": float(prow["joint_conservation"].iloc[0]),
        "n_both": int((icp0 & icp27).sum()),
        "n_icp0_only_absent": int((~icp0 & icp27).sum()),
        "n_icp27_only_absent": int((icp0 & ~icp27).sum()),
        "n_neither": int((~icp0 & ~icp27).sum()),
        "labels": {ICP0G2: "ICP0g2", ICP27G1: "ICP27g1"},
    }


def draw_fig2(d: dict) -> "plt.Figure":
    fig = plt.figure(figsize=(COL_IN, 3.15))
    gs = fig.add_gridspec(2, 1, height_ratios=[1.0, 1.0], hspace=0.88,
                          left=0.305, right=0.965, top=0.855, bottom=0.125)
    ax = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])

    order = d["order"]
    rows = [(d["icp0_present"][order], ICP0G2, VERMILLION),
            (d["icp27_present"][order], ICP27G1, BLUE)]
    n = d["n_genomes"]
    b = d["n_both"]

    for r, (vec, gid, colour) in enumerate(rows):
        for x in np.flatnonzero(vec):
            ax.add_patch(Rectangle((x, r + 0.10), 1.0, 0.80, facecolor="#e2e2e2",
                                   edgecolor="none"))
        for x in np.flatnonzero(~vec):
            ax.add_patch(Rectangle((x, r + 0.10), 1.0, 0.80, facecolor=colour,
                                   edgecolor="none"))
    ax.set_xlim(0, n)
    # y grows downward so that row 0 (ICP0g2) is drawn on top; anything below the
    # matrix therefore has y > 2.
    ax.set_ylim(2.90, -0.05)
    ax.set_yticks([0.5, 1.5])
    ax.set_yticklabels([d["labels"][ICP0G2], d["labels"][ICP27G1]])
    ax.set_xticks([])
    for s in ("left", "bottom"):
        ax.spines[s].set_visible(False)
    ax.tick_params(axis="both", length=0, pad=2)
    ax.set_xlabel("183 complete HSV-1 genomes, by failure pattern", labelpad=1)

    ax.annotate("", xy=(b, 2.06), xytext=(n, 2.06),
                arrowprops=dict(arrowstyle="|-|,widthA=0.20,widthB=0.20",
                                lw=0.7, color=INK, shrinkA=0, shrinkB=0))
    ax.annotate("", xy=(0, 2.06), xytext=(b, 2.06),
                arrowprops=dict(arrowstyle="|-|,widthA=0.20,widthB=0.20",
                                lw=0.7, color="#9a9a9a", shrinkA=0, shrinkB=0))
    ax.text(n, 2.20,
            "%d missed — by one guide\nor the other, never both" % (n - b),
            ha="right", va="top", fontsize=5.7, color=INK)
    ax.text(0, 2.20, "both guides present\n(%d of %d)" % (b, n),
            ha="left", va="top", fontsize=5.7, color=MUTED)

    ax.legend(handles=[Line2D([], [], marker="s", ls="none", ms=4.2, mfc="#e2e2e2",
                              mec="none", label="present"),
                       Line2D([], [], marker="s", ls="none", ms=4.2, mfc=VERMILLION,
                              mec="none", label="ICP0g2 absent"),
                       Line2D([], [], marker="s", ls="none", ms=4.2, mfc=BLUE,
                              mec="none", label="ICP27g1 absent")],
              loc="lower left", bbox_to_anchor=(-0.005, 1.02), ncol=3,
              handletextpad=0.25, columnspacing=0.8, borderaxespad=0.0,
              fontsize=5.9)
    ax.set_title("A   Per-genome presence of the published lead pair",
                 loc="left", pad=17, x=TITLE_X)

    # Panel B -- the four coverage numbers, on an axis zoomed enough to separate the
    # product of marginals from the measured joint.
    items = [("ICP27g1 marginal", d["marginals"][ICP27G1], BLUE),
             ("ICP0g2 marginal", d["marginals"][ICP0G2], VERMILLION),
             ("product of marginals", d["product_of_marginals"], MUTED),
             ("measured joint", d["joint"], GREEN)]
    ypos = np.arange(len(items))[::-1]
    lo = 0.80
    for y, (label, val, colour) in zip(ypos, items):
        ax2.plot([lo, val], [y, y], color=colour, lw=1.6, solid_capstyle="butt",
                 zorder=2)
        ax2.plot([val], [y], marker="o", ms=4.2, mfc="white", mew=1.3, mec=colour,
                 zorder=3)
        ax2.text(val + 0.005, y, f"{val:.4f}", va="center", ha="left", fontsize=6.0,
                 color=INK)
    ax2.set_yticks(ypos)
    ax2.set_yticklabels([i[0] for i in items])
    ax2.set_xlim(lo, 1.045)
    ax2.set_ylim(-0.6, len(items) - 0.4)
    ax2.set_xticks([0.80, 0.85, 0.90, 0.95, 1.00])
    ax2.set_xlabel("fraction of the 183 genomes", labelpad=2)
    ax2.spines["left"].set_visible(False)
    ax2.spines["bottom"].set_bounds(lo, 1.0)
    ax2.tick_params(axis="y", length=0, pad=2)
    ax2.grid(axis="x", color=FAINT, lw=0.4, alpha=0.5)
    ax2.set_axisbelow(True)
    ax2.set_title("B   Coverage is not the product of the marginals",
                  loc="left", pad=4, x=TITLE_X)
    ax2.annotate("joint < product:\nthe two failures are\nanti-correlated,\n"
                 "not independent",
                 xy=(0.870, 0.5), xytext=(0.888, 0.62),
                 fontsize=5.7, color=INK, ha="left", va="center",
                 arrowprops=dict(arrowstyle="-", lw=0.6, color=MUTED,
                                 shrinkA=1, shrinkB=2))
    return fig


# --------------------------------------------------------------------------------------
# Figure 3 -- search-space contraction
# --------------------------------------------------------------------------------------


def fig3_data() -> dict:
    """Conservation across the SpCas9 NGG and SaCas9 NNGRRT candidate spaces.

    Both distributions are read whole from the two stage-3 outputs -- every
    candidate, no binning done upstream:

        results/conservation.tsv          SpCas9 NGG, 20 nt spacer
        results/sacas9/conservation.tsv   SaCas9 NNGRRT, 21 nt spacer

    Counts and the perfectly-conserved fraction are recomputed from those columns
    and cross-checked against `results/summary.json` and
    `results/sacas9/summary.json` in `tests/test_figures.py`.
    """
    spec = {
        "SpCas9  NGG": (DEFAULT_CONSERVATION, RESULTS_DIR / "summary.json", BLUE),
        "SaCas9  NNGRRT": (RESULTS_DIR / "sacas9" / "conservation.tsv",
                           RESULTS_DIR / "sacas9" / "summary.json", VERMILLION),
    }
    spaces = {}
    for label, (tsv, summary_path, colour) in spec.items():
        df = _tsv(tsv, "run_pipeline.py --skip-fetch")
        frac = df["conservation_fraction"].to_numpy(dtype=float)
        published = json.loads(_need(summary_path, "run_pipeline.py").read_text())
        spaces[label] = {
            "conservation": frac,
            "n": int(len(frac)),
            "n_perfect": int((frac >= 1.0).sum()),
            "pct_perfect": 100.0 * float((frac >= 1.0).mean()),
            "median": float(np.median(frac)),
            "mean": float(frac.mean()),
            "colour": colour,
            "published_n": int(published["n_guides"]),
            "published_n_perfect": int(published["conservation_cumulative_counts"]
                                       ["== 1.00 (perfect)"]),
            "published_median": float(published["conservation_median"]),
        }
    labels = list(spaces)
    spaces_n = [spaces[k]["n"] for k in labels]
    return {
        "spaces": spaces,
        "labels": labels,
        "contraction_factor": spaces_n[0] / spaces_n[1],
        "pct_perfect_delta": (spaces[labels[1]]["pct_perfect"]
                              - spaces[labels[0]]["pct_perfect"]),
    }


def draw_fig3(d: dict) -> "plt.Figure":
    fig = plt.figure(figsize=(COL_IN, 3.7))
    gs = fig.add_gridspec(2, 1, height_ratios=[0.72, 1.0], hspace=0.60,
                          left=0.26, right=0.955, top=0.905, bottom=0.115)
    ax = fig.add_subplot(gs[0])
    ax2 = fig.add_subplot(gs[1])

    labels = d["labels"]
    y = np.arange(len(labels))[::-1]
    # Linear, not log: on a log axis a bar's length is not its value, and the whole
    # claim of this panel is that one bar is a tenth of the other.
    widest = max(d["spaces"][lab]["n"] for lab in labels)
    for yy, lab in zip(y, labels):
        s = d["spaces"][lab]
        ax.barh(yy, s["n"], height=0.50, color="#dcdcdc", edgecolor="none", zorder=2)
        ax.barh(yy, s["n_perfect"], height=0.50, color=s["colour"], edgecolor="none",
                zorder=3)
        ax.text(s["n"] + widest * 0.018, yy, f"{s['n']:,}", va="center", ha="left",
                fontsize=6.4, color=INK, zorder=4)
        ax.text(widest * 0.006, yy - 0.34,
                "%d perfectly conserved  (%.1f%%)"
                % (s["n_perfect"], s["pct_perfect"]),
                va="center", ha="left", fontsize=5.5, color=s["colour"], zorder=4)
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xlim(0, widest * 1.22)
    ax.set_ylim(-0.62, len(labels) - 0.38)
    ax.set_xticks([0, 1000, 2000, 3000, 4000])
    ax.set_xticklabels(["0", "1,000", "2,000", "3,000", "4,000"])
    ax.set_xlabel("candidate sites across the 7 target genes", labelpad=2)
    ax.spines["left"].set_visible(False)
    ax.tick_params(axis="y", length=0, pad=2)
    ax.grid(axis="x", color=FAINT, lw=0.4, alpha=0.5)
    ax.set_axisbelow(True)
    ax.legend(handles=[Line2D([], [], marker="s", ls="none", ms=4.2, mfc="#dcdcdc",
                              mec="none", label="all candidates"),
                       Line2D([], [], marker="s", ls="none", ms=4.2, mfc=MUTED,
                              mec="none", label="perfectly conserved (183/183)")],
              loc="lower left", bbox_to_anchor=(-0.005, 1.02), ncol=2,
              handletextpad=0.25, columnspacing=0.8, borderaxespad=0.0, fontsize=5.9)
    ax.set_title("A   NNGRRT costs an order of magnitude in options",
                 loc="left", pad=17, x=_title_x(0.26, 0.955))
    ax.text(d["spaces"][labels[1]]["n"] + widest * 0.17, 0,
            "— %.1f× fewer sites" % d["contraction_factor"],
            fontsize=6.0, color=INK, ha="left", va="center", zorder=4)

    # Panel B: the survival curve of conservation. Identical shapes = the *fraction*
    # that is well conserved is a property of the virus, not of the PAM.
    grid = np.linspace(0.0, 1.0, 501)
    for lab in labels:
        s = d["spaces"][lab]
        surv = np.array([(s["conservation"] >= g).mean() for g in grid])
        ls = "-" if lab is labels[0] else (0, (4, 2))
        ax2.plot(grid, 100.0 * surv, color=s["colour"], lw=1.5, ls=ls,
                 label="%s  (n = %s)" % (lab, f"{s['n']:,}"), zorder=3)
        ax2.plot([1.0], [s["pct_perfect"]], marker="o", ms=4.0, mfc="white",
                 mew=1.3, mec=s["colour"], zorder=4, clip_on=False)
    ax2.set_xlim(0.4, 1.045)
    ax2.set_ylim(0, 104)
    ax2.set_xlabel("cross-isolate conservation (fraction of 183 genomes)", labelpad=2)
    ax2.set_ylabel("% of candidates\nat least this conserved", linespacing=1.3)
    ax2.grid(color=FAINT, lw=0.4, alpha=0.5)
    ax2.set_axisbelow(True)
    ax2.legend(loc="lower left", handlelength=2.2, borderaxespad=0.3, fontsize=6.0)
    ax2.set_title("B   …but the conserved fraction barely moves", loc="left", pad=10,
                  x=_title_x(0.26, 0.955))

    p0 = d["spaces"][labels[0]]["pct_perfect"]
    p1 = d["spaces"][labels[1]]["pct_perfect"]
    ax2.annotate("perfectly conserved:\n%.1f%% vs %.1f%%   (Δ %.1f points)"
                 % (p0, p1, d["pct_perfect_delta"]),
                 xy=(1.0, 0.5 * (p0 + p1)), xytext=(0.585, 41),
                 fontsize=6.0, color=INK, ha="left", va="center",
                 arrowprops=dict(arrowstyle="-", lw=0.7, color=MUTED,
                                 shrinkA=3, shrinkB=5))
    return fig


# --------------------------------------------------------------------------------------
# Figure 4 -- the ICP0 candidate landscape
# --------------------------------------------------------------------------------------

#: Guides that must be visible and named on figure 4, with the role each plays in the
#: argument. The Pareto front is not listed here: it is computed from the data.
FIG4_MARKED = {
    "RL2_4496+": ("ICP0g2 (published)", VERMILLION, "o"),
    "RL2_5335+": ("RL2_5335+ (recommended)", GREEN, "D"),
    "RL2_3441+": ("RL2_3441+ (withdrawn)", ORANGE, "^"),
}

#: The axes of the multi-axis comparison, as (column, short label, lower_is_better).
FIG4_AXES = (
    ("cons_183", "conservation\n183 genomes", False),
    ("nngrrt_le3", "NNGRRT\n≤3 mm", True),
    ("nngrrt_le4", "NNGRRT\n≤4 mm", True),
    ("nngrrn_le3", "NNGRRN\n≤3 mm", True),
    ("nngrrn_le4", "NNGRRN\n≤4 mm", True),
    ("local_gc_200bp", "local GC\n200 bp", True),
)


def fig4_data() -> dict:
    """The 14 screened ICP0/RL2 candidates on every axis the recommendation uses.

    All plotted columns are read from `results/recommendation_table.tsv`, which
    `src/reconcile.py` generates by joining stages 6, 7 and 8 on `guide_id`.

    The Pareto front is NOT read from a file -- `recommendation.md` states it in
    prose. It is recomputed here by calling `src.reconcile.apply_rule`, i.e. the same
    `pareto_front` over the same `PARETO_HIGHER` / `PARETO_LOWER_CORE` axis sets that
    produced the claim, so the figure cannot drift from the document.
    """
    from src.reconcile import apply_rule

    table = _tsv(RESULTS_DIR / "recommendation_table.tsv", "python src/reconcile.py")
    rule = apply_rule(table)

    marked = {g: FIG4_MARKED[g] for g in FIG4_MARKED if g in set(table["guide_id"])}
    absent = sorted(set(FIG4_MARKED) - set(marked))
    if absent:
        raise SystemExit(f"Figure 4 requires {absent} in recommendation_table.tsv.")

    return {
        "table": table,
        "axes": FIG4_AXES,
        "marked": marked,
        "pareto_front": list(rule["pareto_front"]),
        "survivors": list(rule["survivors"]),
        "selected": rule["selected"],
        "n_candidates": int(len(table)),
    }


def _short(gid: str) -> str:
    return gid.replace("RL2_", "")


def draw_fig4(d: dict) -> "plt.Figure":
    table = d["table"].set_index("guide_id")
    axes_spec = d["axes"]
    front = d["pareto_front"]

    fig = plt.figure(figsize=(COL_IN, 4.30))
    ax = fig.add_axes([0.075, 0.655, 0.905, 0.270])
    ax2 = fig.add_axes([0.190, 0.115, 0.775, 0.330])

    # --- Panel A: parallel coordinates -------------------------------------------
    # Each axis is scaled to its own observed range and ORIENTED so that 1.0 is the
    # better end, whichever direction that is for the measure. A line that stays high
    # is good everywhere; the withdrawn candidate's dive is the point of the panel.
    cols = [c for c, _, _ in axes_spec]
    lo, hi = table[cols].min(), table[cols].max()
    span = (hi - lo).replace(0.0, 1.0)
    norm = pd.DataFrame(index=table.index)
    for col, _, lower_is_better in axes_spec:
        raw = (table[col] - lo[col]) / span[col]
        norm[col] = (1.0 - raw) if lower_is_better else raw
    xs = np.arange(len(cols))

    def style_for(gid: str):
        if gid in d["marked"]:
            _, colour, marker = d["marked"][gid]
            return dict(color=colour, lw=1.5, zorder=6, marker=marker, ms=3.4,
                        mfc="white", mew=1.1, mec=colour)
        if gid in front:
            return dict(color=BLUE, lw=1.1, zorder=5, ls=(0, (3, 1.6)), marker="s",
                        ms=2.6, mfc="white", mew=0.9, mec=BLUE)
        return dict(color=FAINT, lw=0.8, zorder=2)

    for gid in table.index:
        ax.plot(xs, norm.loc[gid, cols].to_numpy(), **style_for(gid))

    for i, (col, label, lower_is_better) in enumerate(axes_spec):
        ax.axvline(i, color="#9a9a9a", lw=0.55, zorder=1)
        ax.text(i, 1.50, label, ha="center", va="top", fontsize=5.2, color=INK,
                linespacing=1.25)
        best, worst = ((lo[col], hi[col]) if lower_is_better else (hi[col], lo[col]))
        ax.text(i, 1.07, "%.3g" % best, ha="center", va="bottom", fontsize=5.0,
                color=MUTED)
        ax.text(i, -0.07, "%.3g" % worst, ha="center", va="top", fontsize=5.0,
                color=MUTED)
    ax.set_xlim(-0.55, len(cols) - 0.45)
    ax.set_ylim(-0.30, 1.52)
    ax.set_yticks([])
    ax.set_xticks([])
    for s in ax.spines.values():
        s.set_visible(False)
    ax.annotate("", xy=(-0.48, 1.02), xytext=(-0.48, 0.30),
                arrowprops=dict(arrowstyle="->", lw=0.7, color=MUTED))
    ax.text(-0.42, 0.66, "better", rotation=90, ha="left", va="center",
            fontsize=5.6, color=MUTED)

    fig.text(0.015, 0.985,
             "A   Every screened ICP0 candidate, on every axis (n = %d)"
             % d["n_candidates"], fontsize=8.0, ha="left", va="top")

    handles = [Line2D([], [], color=c, lw=1.5, marker=m, ms=3.4, mfc="white",
                      mew=1.1, mec=c, label=lab)
               for _, (lab, c, m) in d["marked"].items()]
    handles.append(Line2D([], [], color=BLUE, lw=1.1, ls=(0, (3, 1.6)), marker="s",
                          ms=2.6, mfc="white", mew=0.9, mec=BLUE,
                          label="Pareto front, other members"))
    handles.append(Line2D([], [], color=FAINT, lw=0.9, label="other candidates"))
    ax.legend(handles=handles, loc="upper left", bbox_to_anchor=(-0.012, -0.075),
              ncol=2, handlelength=1.7, labelspacing=0.5, handletextpad=0.4,
              columnspacing=1.0, borderaxespad=0.0, fontsize=5.6)

    # --- Panel B: the trade-off the recommendation turns on ----------------------
    xcol, ycol = "nngrrt_le4", "nngrrn_le3"
    for gid, row in table.iterrows():
        if gid in d["marked"]:
            continue
        on_front = gid in front
        ax2.plot([row[xcol]], [row[ycol]],
                 marker="s" if on_front else "o", ms=4.2 if on_front else 3.2,
                 mfc="white" if on_front else "#e2e2e2",
                 mew=1.1 if on_front else 0.7,
                 mec=BLUE if on_front else "#9a9a9a", ls="none", zorder=4)
    for gid, (_, colour, marker) in d["marked"].items():
        row = table.loc[gid]
        ax2.plot([row[xcol]], [row[ycol]], marker=marker, ms=5.4, mfc=colour,
                 mec="white", mew=0.9, ls="none", zorder=6)

    # Label offsets are pure layout: they move text, never a datum.
    offsets = {"RL2_5335+": (-2, 8), "RL2_3364+": (5, -6), "RL2_5080+": (6, 0),
               "RL2_4496+": (7, 0), "RL2_3441+": (0, 7)}
    aligns = {"RL2_5335+": ("left", "bottom"), "RL2_3364+": ("left", "top"),
              "RL2_5080+": ("left", "center"), "RL2_4496+": ("left", "center"),
              "RL2_3441+": ("center", "bottom")}
    for gid in sorted(set(front) | set(d["marked"])):
        row = table.loc[gid]
        colour = d["marked"][gid][1] if gid in d["marked"] else BLUE
        ha, va = aligns.get(gid, ("left", "bottom"))
        note = ""
        if gid == d["selected"]:
            note = "\nselected"
        elif gid == "RL2_3441+":
            note = "\nwithdrawn"
        ax2.annotate(_short(gid) + note, xy=(row[xcol], row[ycol]),
                     xytext=offsets.get(gid, (5, 3)), textcoords="offset points",
                     fontsize=5.5, color=colour, ha=ha, va=va, zorder=7,
                     linespacing=1.2)

    ax2.set_xlabel("GRCh38 NNGRRT sites at ≤ 4 mismatches\n"
                   "(the discriminator: the canonical PAM)", labelpad=2)
    ax2.set_ylabel("NNGRRN sites\nat ≤ 3 mismatches", labelpad=2, linespacing=1.3)
    ax2.set_xlim(-2.2, float(table[xcol].max()) * 1.10)
    ax2.set_ylim(-5.0, float(table[ycol].max()) * 1.18)
    ax2.grid(color=FAINT, lw=0.4, alpha=0.5)
    ax2.set_axisbelow(True)
    fig.text(0.015, 0.510,
             "B   Where the recommendation becomes a judgement",
             fontsize=8.0, ha="left", va="top")
    ax2.annotate("", xy=(0.045, 0.115), xytext=(0.295, 0.415),
                 xycoords="axes fraction", textcoords="axes fraction",
                 arrowprops=dict(arrowstyle="->", lw=0.7, color=MUTED))
    ax2.text(0.310, 0.410, "cleaner on both\nPAM tiers", transform=ax2.transAxes,
             fontsize=5.5, color=MUTED, ha="left", va="bottom", linespacing=1.2)
    return fig


# --------------------------------------------------------------------------------------
# Figure 5 -- the recurrent SNP under ICP0g2
# --------------------------------------------------------------------------------------


def _single_substitution_variants(seqs: dict[str, str], target: str) -> dict[str, list[str]]:
    """Accession -> the target sites at exactly one substitution from `target`.

    Exact and complete for 1 mismatch by the pigeonhole principle: split the target
    in two halves, and a one-substitution copy must match one half verbatim, so
    anchoring on each half in turn cannot miss a hit. Both strands are searched, and
    hits are reported in the target's own orientation.
    """
    n = len(target)
    half = n // 2
    out: dict[str, list[str]] = {}
    for acc, seq in seqs.items():
        found: set[str] = set()
        for probe, orient in ((target, "+"), (revcomp(target), "-")):
            pblocks = (((probe[:half], 0), (probe[half:], half))
                       if orient == "+" else
                       ((probe[:n - half], 0), (probe[n - half:], n - half)))
            for block, off in pblocks:
                i = seq.find(block)
                while i != -1:
                    s = i - off
                    if 0 <= s and s + n <= len(seq):
                        cand = seq[s:s + n]
                        fwd = cand if orient == "+" else revcomp(cand)
                        if sum(1 for a, b in zip(fwd, target) if a != b) == 1:
                            found.add(fwd)
                    i = seq.find(block, i + 1)
        out[acc] = sorted(found)
    return out


def fig5_data() -> dict:
    """The recurrent single-nucleotide variant under the ICP0g2 spacer.

    Not in any results file: `absent_in` is truncated at 25 accessions and records
    only WHICH isolates lack the site, never what they carry instead. Both the
    identity of the variant and its carriers are therefore DISCOVERED here from
    `data/raw/*.fasta`, by enumerating every target site at exactly one substitution
    from ICP0g2's (both strands, pigeonhole-exact) across all 183 genomes and taking
    the most frequent. Nothing about the position or the base change is assumed.

    Carrier metadata is read from `data/manifest.tsv`; records with no country or no
    collection date are counted and shown as their own category rather than dropped.
    """
    pool = _tsv(RESULTS_DIR / "sacas9_benchmark_pool.tsv",
                "run_pipeline.py --benchmark-sacas9")
    manifest = _tsv(DEFAULT_MANIFEST, "run_pipeline.py (stage 1)")
    row = pool[pool["guide_id"] == ICP0G2]
    if row.empty:
        raise SystemExit(f"{ICP0G2} is missing from the stage-6 pool.")
    row = row.iloc[0]
    target = str(row["target_site"])
    spacer = str(row["protospacer"])
    pam = str(row["pam"])

    seqs = _load_genome_seqs(manifest)
    variants = _single_substitution_variants(seqs, target)

    present = {acc: (target in s) or (revcomp(target) in s) for acc, s in seqs.items()}
    counts: dict[str, list[str]] = {}
    for acc, vs in variants.items():
        for v in vs:
            counts.setdefault(v, []).append(acc)
    if not counts:
        raise SystemExit("No single-substitution variant of the ICP0g2 site was found.")
    variant, carriers = max(counts.items(), key=lambda kv: (len(kv[1]), kv[0]))
    carriers = sorted(carriers)

    diffs = [(i, a, b) for i, (a, b) in enumerate(zip(target, variant)) if a != b]
    if len(diffs) != 1:
        raise SystemExit("The dominant variant is not a single substitution.")
    idx0, ref_base, alt_base = diffs[0]

    absent = sorted(a for a, p in present.items() if not p)
    other_variant = sorted(set(absent) - set(carriers))
    other_detail = {a: variants[a] for a in other_variant if variants[a]}

    meta = manifest.set_index("accession")
    years, countries = {}, {}
    for acc in carriers:
        raw_date = meta.at[acc, "collection_date"] if acc in meta.index else None
        m = re.search(r"(1[89]\d{2}|20\d{2})", str(raw_date)) if pd.notna(raw_date) else None
        years[acc] = int(m.group(1)) if m else None
        raw_country = meta.at[acc, "country"] if acc in meta.index else None
        countries[acc] = (str(raw_country).split(":")[0].strip()
                          if pd.notna(raw_country) else None)

    n_year = sum(v is not None for v in years.values())
    n_country = sum(v is not None for v in countries.values())

    return {
        "guide_id": ICP0G2,
        "label": "ICP0g2",
        "spacer": spacer,
        "pam": pam,
        "target": target,
        "variant": variant,
        "variant_index0": idx0,
        "spacer_position": idx0 + 1,
        "ref_base": ref_base,
        "alt_base": alt_base,
        "ref_start": int(row["ref_start"]),
        "n_genomes": int(len(seqs)),
        "carriers": carriers,
        "n_carriers": len(carriers),
        "n_present": int(sum(present.values())),
        "n_absent": len(absent),
        "absent": absent,
        "other_absent": other_variant,
        "other_absent_variants": other_detail,
        "published_n_present": int(row["n_strains_present"]),
        "years": years,
        "countries": countries,
        "n_with_year": n_year,
        "n_missing_year": len(carriers) - n_year,
        "n_with_country": n_country,
        "n_missing_country": len(carriers) - n_country,
        "all_variant_counts": {v: len(a) for v, a in
                               sorted(counts.items(), key=lambda kv: -len(kv[1]))},
    }


def draw_fig5(d: dict) -> "plt.Figure":
    fig = plt.figure(figsize=(COL_IN, 5.00))
    ax = fig.add_axes([0.145, 0.705, 0.835, 0.195])      # A: the spacer
    axy = fig.add_axes([0.175, 0.435, 0.585, 0.140])     # B: dated carriers
    axu = fig.add_axes([0.850, 0.435, 0.080, 0.140])     # B: undated carriers
    axc = fig.add_axes([0.300, 0.195, 0.665, 0.125])     # C: country

    # --- Panel A: the two sequences, base by base --------------------------------
    target, variant, j = d["target"], d["variant"], d["variant_index0"]
    n = len(target)
    nsp = len(d["spacer"])
    for r, (seq, name, colour) in enumerate([(target, "reference", INK),
                                             (variant, "variant", VERMILLION)]):
        for i, ch in enumerate(seq):
            hit = i == j
            face = "#fbe3d2" if hit else ("#f2f2f2" if i < nsp else "#e4e4e4")
            ax.add_patch(Rectangle((i, r + 0.06), 1.0, 0.88, facecolor=face,
                                   edgecolor="white", lw=0.5, zorder=2))
            ax.text(i + 0.5, r + 0.50, ch, ha="center", va="center",
                    fontsize=4.8, family="DejaVu Sans Mono", zorder=3,
                    color=(VERMILLION if hit and r == 1 else
                           (INK if hit else ("#4a4a4a" if i < nsp else MUTED))),
                    fontweight="bold" if hit else "normal")
        ax.text(-0.55, r + 0.50, name, ha="right", va="center", fontsize=6.0,
                color=colour)
    ax.add_patch(Rectangle((j, 0.00), 1.0, 2.00, facecolor="none",
                           edgecolor=VERMILLION, lw=0.9, zorder=4))
    ax.plot([nsp, nsp], [0.02, 1.98], color="#8a8a8a", lw=0.7, zorder=5)

    ax.annotate("%s\u2192%s at spacer position %d"
                % (d["ref_base"], d["alt_base"], d["spacer_position"]),
                xy=(j + 0.5, 0.0), xytext=(j + 0.5, -0.70),
                fontsize=6.2, color=VERMILLION, ha="center", va="bottom",
                arrowprops=dict(arrowstyle="-", lw=0.8, color=VERMILLION,
                                shrinkA=2, shrinkB=1))
    ax.text(nsp / 2, 2.16, "%d nt spacer" % nsp, ha="center", va="top",
            fontsize=5.7, color=MUTED)
    ax.text(nsp + (n - nsp) / 2, 2.16, "%s PAM" % "NNGRRT", ha="center", va="top",
            fontsize=5.7, color=MUTED)
    ax.text(n, 2.72,
            "%d of %d isolates carry the variant; %d carry the reference\n"
            "site; %d carry neither (ambiguous or differently varied)"
            % (d["n_carriers"], d["n_genomes"], d["n_present"],
               d["n_genomes"] - d["n_present"] - d["n_carriers"]),
            ha="right", va="top", fontsize=5.5, color=INK, linespacing=1.35)
    ax.set_xlim(-0.5, n + 0.5)
    ax.set_ylim(3.60, -1.15)
    ax.axis("off")

    fig.text(0.015, 0.988, "A   The ICP0g2 spacer and its recurrent variant",
             fontsize=8.0, ha="left", va="top")
    fig.text(0.015, 0.945,
             "HSV-1 %s, reference positions %s–%s (both ICP0 repeat copies)"
             % ("NC_001806", f"{d['ref_start']:,}",
                f"{d['ref_start'] + n - 1:,}"),
             fontsize=5.6, ha="left", va="top", color=MUTED)

    # --- Panel B: collection year, with the undated carriers kept in view ---------
    # The undated carriers get their OWN axis rather than a made-up year: a hatched
    # bar parked at the right-hand end of a real year axis is a fabricated date.
    yrs = sorted(y for y in d["years"].values() if y is not None)
    lo, hi = (min(yrs), max(yrs)) if yrs else (2000, 2000)
    bins = np.arange(lo - 2.5, hi + 5.0, 5.0)
    counts, _ = np.histogram(yrs, bins=bins)
    top = max(int(counts.max()) if len(counts) else 1, d["n_missing_year"])
    axy.hist(yrs, bins=bins, color=VERMILLION, edgecolor="white", lw=0.6, zorder=3)
    axy.set_xlim(bins[0] - 1.5, bins[-1] + 1.5)
    axy.set_xticks(np.arange(np.ceil(lo / 10) * 10, hi + 11, 10))
    axy.set_ylim(0, int(counts.max()) + 1.35 if len(counts) else 2.0)
    axy.set_yticks(np.arange(0, int(counts.max()) + 1) if len(counts) else [0])
    axy.set_xlabel("collection year", labelpad=2)
    axy.set_ylabel("carriers", labelpad=2)
    axy.grid(axis="y", color=FAINT, lw=0.4, alpha=0.5)
    axy.set_axisbelow(True)
    axy.text(0.0, 1.05, "%d of %d carriers are dated  —  note the two y scales"
             % (d["n_with_year"], d["n_carriers"]), transform=axy.transAxes,
             fontsize=5.5, color=MUTED, ha="left", va="bottom")

    axu.bar([0], [d["n_missing_year"]], width=0.62, color="none",
            edgecolor=MUTED, lw=0.8, hatch="////", zorder=3)
    axu.text(0, d["n_missing_year"] * 1.05, str(d["n_missing_year"]),
             ha="center", va="bottom", fontsize=6.0, color=INK)
    axu.set_xlim(-0.62, 0.62)
    axu.set_ylim(0, d["n_missing_year"] * 1.35)
    axu.set_xticks([0])
    axu.set_xticklabels(["no date"], fontsize=5.8)
    axu.set_yticks([0, 5, 10, 15])
    axu.tick_params(axis="y", labelsize=5.6)
    axu.grid(axis="y", color=FAINT, lw=0.4, alpha=0.5)
    axu.set_axisbelow(True)

    fig.text(0.015, 0.655, "B   Carriers by collection year",
             fontsize=8.0, ha="left", va="top")

    # --- Panel C: country, same honesty about missingness ------------------------
    named = [c for c in d["countries"].values() if c is not None]
    tally = pd.Series(named).value_counts() if named else pd.Series(dtype=int)
    labels = list(tally.index) + ["not reported"]
    values = [int(v) for v in tally.to_numpy()] + [d["n_missing_country"]]
    ypos = np.arange(len(labels))[::-1]
    for y, lab, val in zip(ypos, labels, values):
        reported = lab != "not reported"
        axc.barh(y, val, height=0.55, color=VERMILLION if reported else "none",
                 edgecolor=VERMILLION if reported else MUTED,
                 lw=0.0 if reported else 0.8,
                 hatch=None if reported else "////", zorder=3)
        axc.text(val + max(values) * 0.025, y, str(val), va="center", ha="left",
                 fontsize=6.0, color=INK)
    axc.set_yticks(ypos)
    axc.set_yticklabels(labels)
    axc.set_xlim(0, max(values) * 1.15)
    axc.set_xticks(np.arange(0, max(values) + 1, 5))  # counts are integers
    axc.set_ylim(-0.6, len(labels) - 0.4)
    axc.set_xlabel("carrier isolates", labelpad=2)
    axc.spines["left"].set_visible(False)
    axc.tick_params(axis="y", length=0, pad=2)
    axc.grid(axis="x", color=FAINT, lw=0.4, alpha=0.5)
    axc.set_axisbelow(True)

    fig.text(0.015, 0.345, "C   Carriers by country of collection",
             fontsize=8.0, ha="left", va="top")
    fig.text(0.015, 0.022,
             "%d of the %d carriers report no country and %d no collection date.\n"
             "Those records are shown, not dropped: the variant's geography and\n"
             "date of first appearance are genuinely unknown from this corpus."
             % (d["n_missing_country"], d["n_carriers"], d["n_missing_year"]),
             fontsize=5.4, color=MUTED, ha="left", va="bottom", linespacing=1.45)
    return fig


# --------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------

FIGURES = {
    1: (fig1_data, draw_fig1, "Resolution floor: P(escape) versus guide count"),
    2: (fig2_data, draw_fig2, "Joint versus marginal coverage of the lead pair"),
    3: (fig3_data, draw_fig3, "Search-space contraction under NNGRRT"),
    4: (fig4_data, draw_fig4, "The ICP0 candidate landscape"),
    5: (fig5_data, draw_fig5, "The recurrent SNP under the ICP0g2 spacer"),
}


def save_figure(fig: "plt.Figure", number: int, outdir: Path) -> list[Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    png = outdir / f"fig{number}.png"
    pdf = outdir / f"fig{number}.pdf"
    fig.savefig(png, dpi=300, format="png", metadata=_MPL_PNG_METADATA)
    fig.savefig(pdf, format="pdf", metadata=_MPL_PDF_METADATA)
    return [png, pdf]


def build(numbers=(1, 2, 3, 4, 5), outdir: Path = FIGURE_DIR) -> dict[int, list[Path]]:
    written: dict[int, list[Path]] = {}
    with plt.rc_context(RC):
        for n in numbers:
            data_fn, draw_fn, title = FIGURES[n]
            LOG.info("figure %d -- %s", n, title)
            fig = draw_fn(data_fn())
            written[n] = save_figure(fig, n, outdir)
            plt.close(fig)
            for p in written[n]:
                LOG.info("  wrote %s (%d bytes)", p, p.stat().st_size)
    return written


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--outdir", type=Path, default=FIGURE_DIR,
                        help="directory for figN.png / figN.pdf (default: figures/)")
    parser.add_argument("--figure", type=int, action="append", choices=sorted(FIGURES),
                        help="render only this figure (repeatable; default: all five)")
    parser.add_argument("--check-deterministic", action="store_true",
                        help="render twice and verify the bytes are identical")
    parser.add_argument("--verbose", action="store_true")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    add_arguments(parser)
    args = parser.parse_args(argv)
    setup_logging(args.verbose)
    logging.getLogger().setLevel(logging.INFO)

    numbers = tuple(sorted(set(args.figure))) if args.figure else tuple(sorted(FIGURES))
    written = build(numbers, args.outdir)

    if args.check_deterministic:
        first = {p: _digest(p) for ps in written.values() for p in ps}
        build(numbers, args.outdir)
        bad = [str(p) for p, h in first.items() if _digest(p) != h]
        if bad:
            LOG.error("NOT deterministic: %s", ", ".join(bad))
            return 1
        LOG.info("deterministic: %d files reproduced byte-for-byte", len(first))

    print("\nWrote %d figure(s) to %s:" % (len(written), args.outdir))
    for n in sorted(written):
        for p in written[n]:
            print(f"  {p.relative_to(PROJECT_ROOT) if PROJECT_ROOT in p.parents else p}"
                  f"  {p.stat().st_size:,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
